development:
  clients:
    default:
      database: log_db
      hosts:
        - localhost:27017
      options:

  options:

  driver_options:

test:
  clients:
    default:
      database: auth_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
